apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      name: {{ .Release.Name }}-ui
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      serviceAccountName: {{ .Release.Name }}-ui
      containers:
        - name: velero-ui
          image: "ghcr.io/hsmade/velero-ui:{{ .Values.pod.imageVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            {{- .Values.pod.env | toYaml | nindent 12 }}
      restartPolicy: Always
