apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: velero-ui
          image: "ghcr.io/hsmade/velero-ui:{{ .Values.pod.imageVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
