{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName }}
{{- end }}
  ingressClassName: {{ .Values.ingress.ingressClassname }}
  rules:
    - http:
        host: {{ .Values.ingress.hostname }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
{{ end }}
