apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-ui
rules:
  - apiGroups:
      - velero.io
    resources:
      - "*"
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-ui
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ .Release.Name }}-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ui
---
